/**
 * Default starter prompts shown in the topic picker.
 * These are used as a fallback / pre-render and can be regenerated by
 * scripts/generate-starters.mjs to be more specific to the deliverable content.
 */

export const DEFAULT_STARTERS = {
  all: [
    'What did interviewees say is the most painful part of monthly bill review?',
    'Who is the strongest beachhead vertical and why?',
    'How does Clear Current compare to EnergyCAP and Arcadia?',
  ],
  d0: [
    'What are the five proofs in the Decision Brief?',
    'What three calls does the Decision Brief recommend acting on?',
    'What are the open questions the team still needs to resolve?',
  ],
  d1: [
    'Which trigger has the highest urgency across verticals?',
    'When do anomaly-driven triggers cluster seasonally?',
    'How should Clear Current respond to budget-cycle triggers?',
  ],
  d2: [
    'When is the best time to reach higher-ed buyers?',
    'Which vertical has the longest sales calendar window?',
    'How does the calendar align with rate-case filings?',
  ],
  d3: [
    'What does the monthly bill review journey look like before and after Clear Current?',
    'Which journey produces the strongest ROI story?',
    'How is the chargeback / departmental billing journey different from anomaly response?',
  ],
  d4: [
    'Which product module should Clear Current build first?',
    'What are the honest gaps in the proposed module set?',
    'How are the modules sequenced across the three phases?',
  ],
  d5: [
    'Why was the recommended beachhead vertical chosen?',
    'What is the ARR path to Series A?',
    'Which verticals are explicitly deferred and why?',
  ],
  d6: [
    'What are the three poles of the competitive landscape?',
    'Where does Clear Current win against EnergyCAP?',
    'What are the white-space gaps competitors leave open?',
  ],
  d7: [
    'What is the six-beat investor narrative arc?',
    'What is the strongest objection investors raise, and the answer?',
    'Which evidence carries the most weight in the pitch?',
  ],
  d8: [
    'What are the beachhead ICPs in the GTM playbook?',
    'How does the land-expand-retain motion work?',
    'What kills deals in the current sales motion?',
  ],
  interviews: [
    'What did the healthcare interviewees say about budget cycles?',
    'Which interviewee gave the strongest quote on demand charges?',
    'How did Texas State describe the bill multiplier error?',
  ],
  secondary: [
    'How big is the commercial energy management SaaS market?',
    'What does the Arcadia competitive report say about positioning?',
    'Which secondary claims are well-verified versus uncertain?',
  ],
}
