/**
 * Topic catalog for the picker UI. Mirrors api/_lib/topics.js — keep in sync.
 *
 * Each topic has a tagline shown in the picker card and 3 starter questions
 * loaded from chat-starters.json (generated by scripts/generate-starters.mjs).
 */

export const TOPIC_GROUPS = [
  {
    id: 'all',
    label: 'Everything',
    topics: [
      {
        id: 'all',
        label: 'Explore all research',
        tagline:
          'Ask about anything across the deliverables, interviews, and secondary research.',
        accent: 'navy',
      },
    ],
  },
  {
    id: 'deliverables',
    label: 'Synthesized deliverables',
    topics: [
      {
        id: 'd0',
        label: 'D0 — Decision Brief',
        tagline: 'Five proofs, three open questions, three calls.',
        accent: 'yellow',
      },
      {
        id: 'd1',
        label: 'D1 — Engagement Trigger Map',
        tagline: 'When buyers actually pick up the phone.',
        accent: 'yellow',
      },
      {
        id: 'd2',
        label: 'D2 — Seasonal Energy Calendar',
        tagline: 'Twelve months of when to reach each vertical.',
        accent: 'yellow',
      },
      {
        id: 'd3',
        label: 'D3 — Customer Journey Maps',
        tagline: 'Five journeys, before and after Clear Current.',
        accent: 'yellow',
      },
      {
        id: 'd4',
        label: 'D4 — Product Module Recommendations',
        tagline: 'What to build, in what order.',
        accent: 'yellow',
      },
      {
        id: 'd5',
        label: 'D5 — Market Opportunity Heatmap',
        tagline: 'Scored verticals and the path to Series A.',
        accent: 'yellow',
      },
      {
        id: 'd6',
        label: 'D6 — Competitive Intelligence',
        tagline: 'Three poles of competitors, three white-space gaps.',
        accent: 'yellow',
      },
      {
        id: 'd7',
        label: 'D7 — Investor Narrative',
        tagline: 'Six-beat arc with receipts and an objection book.',
        accent: 'yellow',
      },
      {
        id: 'd8',
        label: 'D8 — GTM Strategy Playbook',
        tagline: 'ICPs, tracks, pricing, and what kills deals.',
        accent: 'yellow',
      },
    ],
  },
  {
    id: 'sources',
    label: 'Source data',
    topics: [
      {
        id: 'interviews',
        label: 'Primary Interviews',
        tagline: '14 founder interviews with energy and facilities leaders.',
        accent: 'green',
      },
      {
        id: 'secondary',
        label: 'Secondary Data',
        tagline: 'Market sizing, competitive intel, and analyst research.',
        accent: 'green',
      },
    ],
  },
]

export const ALL_TOPICS = TOPIC_GROUPS.flatMap((g) => g.topics)

export function getTopic(id) {
  return ALL_TOPICS.find((t) => t.id === id) || ALL_TOPICS[0]
}

/** Map current page path → topic id, used for auto-selection. */
const PATH_TO_TOPIC = {
  '/': 'd0',
  '/triggers': 'd1',
  '/calendar': 'd2',
  '/journeys': 'd3',
  '/modules': 'd4',
  '/market': 'd5',
  '/competition': 'd6',
  '/investor': 'd7',
  '/gtm': 'd8',
  '/chat': 'all',
}

export function topicForPath(pathname) {
  return PATH_TO_TOPIC[pathname] || null
}
